Update `Dioxus.toml` and fixed some problem
DioxusLabs/cli pull request #10
Opened 2022-02-14 01:00 UTC by mrxiaozhuox

2022-02-15 16:58 UTC, jkelleyrtp commented on src/builder.rs
> +        panic!("Bindgen build failed");
Let's add a note here about how bindgen versions might be out of date and then explicitly list the bindgen version dioxus is using (0.2.79) with some steps on how to update their version.

2022-02-15 17:00 UTC, jkelleyrtp requested changes
Just some naming things but overall things look good. 

Now that we handle assets, the final thing left to be at trunk parity is 
1) checking bindgen version of target crate
2) wasm-opt management

For 1) lets's just add better logging on the catch_unwind

We'll address 2) later.

2022-02-17 11:29 UTC, mrxiaozhuox commented on src/builder.rs
> +        panic!("Bindgen build failed");
just add it in the `panic info` ?

2022-02-17 16:27 UTC, jkelleyrtp approved these changes

2022-02-17 16:27 UTC, merged