Complete basic version development
DioxusLabs/cli pull request #7
Opened 2022-01-22 14:23 UTC by mrxiaozhuox

Complete basic version development...

2022-01-23 03:36 UTC, jkelleyrtp commented on src/builder.rs
> +pub fn build(config: &CrateConfig, dist: PathBuf) -> Result<()> {
dist should be part of crateconfig

2022-01-23 04:12 UTC, mrxiaozhuox commented on src/builder.rs
> +pub fn build(config: &CrateConfig, dist: PathBuf) -> Result<()> {
now I'm define the `Dioxus.toml`, This part may be discarded.

2022-01-23 14:53 UTC, mrxiaozhuox commented
I'm try to bind `html` to `rsx`: if `html` file update, re-translate and rebuild the project, then the `html` components can use in `rs`

2022-01-25 06:59 UTC, jkelleyrtp requested changes

2022-01-25 06:59 UTC, jkelleyrtp commented on src/builder.rs
> +        }
The more "idiomatic rust" way of doing this is to just let the cfg return
```
let target_file = if cfg!(windows) {
        res_path.set_extension("exe");
        format!("{}.exe", &file_name)
    } else {
        file_name
    };
```

2022-01-25 06:59 UTC, jkelleyrtp commented on src/cli/cfg.rs
> +    pub platform: Option<String>,
structopt lets you plug in defaults without the options, which will make the code logic cleaner.

```

      /// Build platform: support Web & Desktop [default: "web"]
      #[structopt(long, default = "web")]
      pub platform: String,
```

Do this for all the optional fields that we eventually override or need to check.

2022-01-25 06:59 UTC, jkelleyrtp commented on src/cli/serve/mod.rs
> +                | crate::ExecutableType::Example(name) => {
make a helper method on executable type that will give you the `name` instead of this weird matching thing.

2022-01-25 06:59 UTC, jkelleyrtp commented on src/cli/serve/mod.rs
> +        if self.serve.platform.is_some() && self.serve.platform.unwrap().to_uppercase() == "DESKTOP" {
if you use the structopt default thing, then you can just match here

```rust
match self.serve.platform.as_str() {
   "web" => {}
   "desktop" => {}   
}
``

2022-01-25 06:59 UTC, jkelleyrtp commented on src/main.rs
> +        // }
lets remove these comment lines

2022-01-25 06:59 UTC, jkelleyrtp commented on src/server/mod.rs
> +                    | DebouncedEvent::Rename(e, _) => {
maybe a helper function that gets the pathbuf out of debounced event? to declutter this code?

2022-01-25 06:59 UTC, jkelleyrtp commented on src/server/mod.rs
> +                        let mut reload = false;
`should_reload` is a better name

2022-01-25 06:59 UTC, jkelleyrtp commented on src/server/mod.rs
> +        }
this is a polling loop that causes high CPU usage. replace this with a channel!

2022-01-25 06:59 UTC, jkelleyrtp commented on src/config.rs
> +        }
if dioxus.toml is not found, then we should just use the defaults (and log that we didn't find it) instead of erroring out. Some library crates might want to have a few examples, but don't want to bother configuring dioxus.

2022-01-25 06:59 UTC, jkelleyrtp commented on src/config.rs
> +            }
this pattern is the `map_err` pattern

```rust
toml::from_str::<DioxusConfig>(&meta_str).map_err(|e| Err(Unique("")))
```

2022-01-25 09:09 UTC, mrxiaozhuox commented on src/server/mod.rs
> +        }
I've add a `sleep` 1.2 sec

2022-01-25 09:15 UTC, mrxiaozhuox commented on src/cli/cfg.rs
> +    pub platform: Option<String>,
`#[structopt(long, default_value = "web")]`

2022-01-25 09:34 UTC, mrxiaozhuox commented on src/server/mod.rs
> +                    | DebouncedEvent::Rename(e, _) => {
sorry I can't understand this.

2022-01-25 12:32 UTC, mrxiaozhuox commented
Wait, I think the `auto-reload` have some problem.

2022-01-28 03:39 UTC, jkelleyrtp approved these changes

2022-01-28 03:45 UTC, merged

2022-01-28 03:46 UTC, jkelleyrtp commented
Yay!!!!!